const data = [
	{
		artist: 'Green Day',
		cd: 'Dookie',
		img: './src/assets/img/img_gd.jfif',
		songs: [
			{ name: 'Burnout', time: 136 },
			{ name: 'Chump', time: 162 },
			{ name: 'Longview', time: 227 },
			{ name: 'Welcome to Paradise', time: 221 },
			{ name: 'Pulling Teeth', time: 141 },
			{ name: 'Basket Case', time: 181 },
			{ name: 'She', time: 141 },
			{ name: 'Sassafras Roots', time: 171 },
			{ name: 'When I Come Around', time: 204 },
			{ name: 'Coming Clean', time: 67 },
			{ name: 'Emenius Sleepus', time: 121 },
			{ name: 'In the End', time: 102 },
			{ name: 'F.O.D.', time: 284 },
		],
	},
	{
		artist: 'Red Hot Chili Peppers',
		cd: 'Californication',
		img: './src/assets/img/img_rhcp.jfif',
		songs: [
			{ name: 'Around The World', time: 238 },
			{ name: 'Parallel Universe', time: 259 },
			{ name: 'Scar Tissue', time: 217 },
			{ name: 'Otherside', time: 255 },
			{ name: 'Get on Top', time: 203 },
			{ name: 'Californication', time: 330 },
			{ name: 'Easily', time: 185 },
			{ name: 'Porcelain', time: 168 },
			{ name: 'Emit Remmus', time: 256 },
			{ name: 'I Like Dirt', time: 162 },
			{ name: 'This Velvet Glove', time: 225 },
			{ name: 'Savior', time: 288 },
			{ name: 'Purple Stain', time: 245 },
			{ name: 'Right on Time', time: 177 },
			{ name: "Road Trippin'", time: 225 },
		],
	},
	{
		artist: 'Misfits',
		cd: 'Famous Monsters',
		img: './src/assets/img/img_mis.jfif',
		songs: [
			{ name: 'Kong at the Gates', time: 73 },
			{ name: 'The Forbidden Zone', time: 115 },
			{ name: 'Lost in Space', time: 172 },
			{ name: 'Dust to Dust', time: 142 },
			{ name: 'Crawling Eye', time: 95 },
			{ name: 'Witch Hunt', time: 102 },
			{ name: 'Scream!', time: 180 },
			{ name: 'Saturday Night', time: 160 },
			{ name: 'Pumpkin Head', time: 116 },
			{ name: 'Scarecrow Man', time: 104 },
			{ name: 'Die Monster Die', time: 96 },
			{ name: 'Living Hell', time: 98 },
			{ name: 'Descending Angel', time: 160 },
			{ name: 'Them', time: 124 },
			{ name: 'Fiend Club', time: 146 },
		],
	},
	{
		artist: 'Nickelback',
		cd: 'All the Right Reasons',
		img: './src/assets/img/img_nik.jfif',
		songs: [
			{ name: 'Animals', time: 214 },
			{ name: 'Far Away', time: 239 },
			{ name: 'Fight For All the Wrong Reasons', time: 193 },
			{ name: 'Follow You Home', time: 240 },
			{ name: 'If Everyone Cared', time: 229 },
			{ name: 'Photograph', time: 259 },
			{ name: 'Rockstar', time: 255 },
			{ name: "Savin' Me", time: 222 },
			{ name: 'Side of a Bullet', time: 177 },
			{ name: "Someone That You're With", time: 227 },
			{ name: 'Throw Yourself Away', time: 216 },
			{ name: 'Woke Up This Morning', time: 218 },
		],
	},
	{
		artist: 'Linkin Park',
		cd: 'Meteora',
		img: './src/assets/img/img_lp.jfif',
		songs: [
			{ name: 'Breaking the Habit', time: 192 },
			{ name: "Don't Stay", time: 171 },
			{ name: 'Easier to Run', time: 207 },
			{ name: 'Faint', time: 156 },
			{ name: 'Figure.09', time: 199 },
			{ name: 'Foreword', time: 13 },
			{ name: 'From the Inside', time: 171 },
			{ name: 'Hit the Floor', time: 177 },
			{ name: 'Lying From You', time: 177 },
			{ name: 'Numb', time: 187 },
			{ name: "Nobody's Listening", time: 178 },
			{ name: 'Session', time: 147 },
			{ name: 'Somewhere I Belong', time: 213 },
			{ name: 'Wastelands', time: 187 },
		],
	},
	{
		artist: 'Foo Fighters',
		cd: 'The Colour and the Shape',
		img: './src/assets/img/img_ff.jfif',
		songs: [
			{ name: 'Doll', time: 152 },
			{ name: 'Enough Space', time: 178 },
			{ name: 'Everlong', time: 250 },
			{ name: 'February Stars', time: 266 },
			{ name: 'Hey, Johnny Park!', time: 252 },
			{ name: 'Monkey Wrench', time: 230 },
			{ name: 'My Hero', time: 259 },
			{ name: 'My Poor Brain', time: 220 },
			{ name: 'New Way Home', time: 309 },
			{ name: 'See You', time: 204 },
			{ name: 'Up in Arms', time: 148 },
			{ name: 'Walking After You', time: 268 },
		],
	},
	{
		artist: 'Avenged Sevenfold',
		cd: 'City of Evil',
		img: './src/assets/img/img_ax7.jfif',
		songs: [
			{ name: 'Bat Country', time: 312 },
			{ name: 'Beast and the Harlot', time: 326 },
			{ name: 'Betrayed', time: 264 },
			{ name: 'Blinded in Chains', time: 343 },
			{ name: 'Burn It Down', time: 325 },
			{ name: 'M.I.A.', time: 543 },
			{ name: 'Seize the Day', time: 328 },
			{ name: 'Sidewinder', time: 343 },
			{ name: 'Strength of the World', time: 372 },
			{ name: 'The Wicked End', time: 308 },
			{ name: 'Trashed and Scattered', time: 328 },
			{ name: 'Unholy Confessions', time: 269 },
		],
	},
];
export default data;
